version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8082:80"
    depends_on:
      - backend1
      - backend2

  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SPRING_PROFILES_ACTIVE=backend1
    ports:
      - "8080:8080"
    volumes:
      - ./target:/target
      - sqlite-data:/app/db
    depends_on:
      - redis-server

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SPRING_PROFILES_ACTIVE=backend2
    ports:
      - "8081:8081"
    volumes:
      - ./target:/target
      - sqlite-data:/app/db
    depends_on:
      - redis-server

  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
      - redis-data:/data
    command: ["redis-server", "/redis.conf"]

volumes:
  sqlite-data:
  redis-data: