version: '3.8'
services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: backend1
    environment:
      - SPRING_PROFILES_ACTIVE=backend1
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app/target
      - ./db:/app/db
    depends_on:
      - redis-server

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: backend2
    environment:
      - SPRING_PROFILES_ACTIVE=backend2
    ports:
      - "8081:8081"
    volumes:
      - ./target:/app/target
      - ./db:/app/db
    depends_on:
      - redis-server

  redis-server:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/app/redis.conf
      - redis-data:/app/data
    command: ["redis-server", "/app/redis.conf"]
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2

volumes:
  sqlite-data:
  redis-data: